package rtsp

import (
	"io"
	"sync"

	"github.com/im-pingo/liveforge/core"
	"github.com/im-pingo/liveforge/pkg/avframe"
	pkgrtp "github.com/im-pingo/liveforge/pkg/rtp"
	pionrtp "github.com/pion/rtp/v2"
	pioncodecs "github.com/pion/rtp/v2/codecs"
)

// RTSPSubscriber implements RTSP playback via TCP interleaved transport.
type RTSPSubscriber struct {
	id      string
	options core.SubscribeOptions
	writer  io.Writer // TCP conn for interleaved mode

	videoPacketizer pionrtp.Packetizer
	audioPacketizer pionrtp.Packetizer
	// Fallback for codecs without pion Payloader (AAC, etc.)
	customAudioPkt pkgrtp.Packetizer
	customAudioSes *pkgrtp.Session

	videoChannel uint8 // TCP interleaved channel for video RTP
	audioChannel uint8 // TCP interleaved channel for audio RTP

	prevVideoDTS int64
	prevAudioDTS int64
	sendCount    int

	mu     sync.Mutex
	closed bool
	done   chan struct{}
}

var _ core.Subscriber = (*RTSPSubscriber)(nil)

// NewRTSPSubscriber creates a new RTSP subscriber for TCP interleaved mode.
func NewRTSPSubscriber(id string, info *avframe.MediaInfo, writer io.Writer, videoChannel, audioChannel uint8) (*RTSPSubscriber, error) {
	sub := &RTSPSubscriber{
		id:           id,
		options:      core.DefaultSubscribeOptions(),
		writer:       writer,
		videoChannel: videoChannel,
		audioChannel: audioChannel,
		done:         make(chan struct{}),
	}

	if info.VideoCodec != 0 {
		pt := codecDefaultPT(info.VideoCodec)
		payloader := pionPayloaderForCodec(info.VideoCodec)
		if payloader != nil {
			sub.videoPacketizer = pionrtp.NewPacketizer(
				pkgrtp.DefaultMTU-12, // payload MTU
				pt,
				0, // SSRC auto-generated by pion
				payloader,
				pionrtp.NewRandomSequencer(),
				90000, // video clock rate
			)
		}
	}

	if info.AudioCodec != 0 {
		pt := codecDefaultPT(info.AudioCodec)
		clockRate := audioClockRate(info)
		payloader := pionPayloaderForCodec(info.AudioCodec)
		if payloader != nil {
			sub.audioPacketizer = pionrtp.NewPacketizer(
				pkgrtp.DefaultMTU-12,
				pt,
				0,
				payloader,
				pionrtp.NewRandomSequencer(),
				clockRate,
			)
		} else {
			// Fallback to custom packetizer for codecs pion doesn't support
			p, err := pkgrtp.NewPacketizer(info.AudioCodec)
			if err != nil {
				return nil, err
			}
			sub.customAudioPkt = p
			sub.customAudioSes = pkgrtp.NewSession(pt, clockRate)
		}
	}

	return sub, nil
}

// pionPayloaderForCodec returns a pion Payloader for the given codec, or nil.
func pionPayloaderForCodec(codec avframe.CodecType) pionrtp.Payloader {
	switch codec {
	case avframe.CodecH264:
		return &pioncodecs.H264Payloader{}
	case avframe.CodecVP8:
		return &pioncodecs.VP8Payloader{}
	case avframe.CodecVP9:
		return &pioncodecs.VP9Payloader{}
	case avframe.CodecOpus:
		return &pioncodecs.OpusPayloader{}
	case avframe.CodecG711U, avframe.CodecG711A:
		return &pioncodecs.G711Payloader{}
	case avframe.CodecG722:
		return &pioncodecs.G722Payloader{}
	default:
		return nil
	}
}

func (s *RTSPSubscriber) ID() string                     { return s.id }
func (s *RTSPSubscriber) Options() core.SubscribeOptions { return s.options }

func (s *RTSPSubscriber) OnData(data []byte) error {
	return nil
}

func (s *RTSPSubscriber) Close() error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if !s.closed {
		s.closed = true
		close(s.done)
	}
	return nil
}

// SendFrame packetizes an AVFrame and sends it via TCP interleaved transport.
func (s *RTSPSubscriber) SendFrame(frame *avframe.AVFrame) error {
	s.mu.Lock()
	if s.closed {
		s.mu.Unlock()
		return nil
	}
	s.mu.Unlock()

	if frame.MediaType.IsVideo() {
		return s.sendVideo(frame)
	} else if frame.MediaType.IsAudio() {
		return s.sendAudio(frame)
	}
	return nil
}

func (s *RTSPSubscriber) sendVideo(frame *avframe.AVFrame) error {
	if s.videoPacketizer == nil {
		return nil
	}

	// Convert payload to Annex-B for pion's H264Payloader
	payload := pkgrtp.ToAnnexB(frame.Payload, frame.FrameType == avframe.FrameTypeSequenceHeader)

	// Compute sample delta (90kHz clock)
	var samples uint32
	if s.prevVideoDTS > 0 && frame.DTS > s.prevVideoDTS {
		samples = uint32((frame.DTS - s.prevVideoDTS) * 90)
	}
	s.prevVideoDTS = frame.DTS

	pkts := s.videoPacketizer.Packetize(payload, samples)
	return s.sendPackets(pkts, s.videoChannel)
}

func (s *RTSPSubscriber) sendAudio(frame *avframe.AVFrame) error {
	if s.audioPacketizer != nil {
		var samples uint32
		if s.prevAudioDTS > 0 && frame.DTS > s.prevAudioDTS {
			clockRate := uint32(44100) // default
			samples = uint32(frame.DTS-s.prevAudioDTS) * clockRate / 1000
		}
		s.prevAudioDTS = frame.DTS
		pkts := s.audioPacketizer.Packetize(frame.Payload, samples)
		return s.sendPackets(pkts, s.audioChannel)
	}

	// Fallback to custom packetizer
	if s.customAudioPkt == nil {
		return nil
	}
	pkts, err := s.customAudioPkt.Packetize(frame, pkgrtp.DefaultMTU)
	if err != nil {
		return err
	}
	wrapped := s.customAudioSes.WrapPackets(pkts, frame.DTS)
	return s.sendPackets(wrapped, s.audioChannel)
}

func (s *RTSPSubscriber) sendPackets(pkts []*pionrtp.Packet, channel uint8) error {
	for _, pkt := range pkts {
		data, err := pkt.Marshal()
		if err != nil {
			return err
		}
		s.sendCount++
		if err := WriteInterleaved(s.writer, channel, data); err != nil {
			return err
		}
	}
	return nil
}

// Done returns a channel that is closed when the subscriber is closed.
func (s *RTSPSubscriber) Done() <-chan struct{} {
	return s.done
}

// audioClockRate returns the RTP clock rate for the audio codec.
func audioClockRate(info *avframe.MediaInfo) uint32 {
	switch info.AudioCodec {
	case avframe.CodecOpus:
		return 48000
	case avframe.CodecG711U, avframe.CodecG711A, avframe.CodecG722, avframe.CodecG729, avframe.CodecSpeex:
		return 8000
	case avframe.CodecMP3:
		return 90000
	case avframe.CodecAAC:
		if info.SampleRate > 0 {
			return uint32(info.SampleRate)
		}
		return 44100
	default:
		return 44100
	}
}
