package rtsp

import (
	"io"
	"math/rand"
	"sync"
	"sync/atomic"
	"time"

	"github.com/im-pingo/liveforge/core"
	"github.com/im-pingo/liveforge/pkg/avframe"
	pkgrtp "github.com/im-pingo/liveforge/pkg/rtp"
	pionrtp "github.com/pion/rtp/v2"
	pioncodecs "github.com/pion/rtp/v2/codecs"
)

// RTSPSubscriber implements RTSP playback via TCP interleaved or UDP transport.
type RTSPSubscriber struct {
	id      string
	options core.SubscribeOptions
	writer  io.Writer // TCP conn for interleaved mode (nil in UDP mode)

	videoPacketizer pionrtp.Packetizer
	audioPacketizer pionrtp.Packetizer
	// Fallback for codecs without pion Payloader (AAC, etc.)
	customAudioPkt pkgrtp.Packetizer
	customAudioSes *pkgrtp.Session

	videoChannel uint8 // TCP interleaved channel for video RTP
	audioChannel uint8 // TCP interleaved channel for audio RTP

	// UDP transport (non-nil when client negotiated UDP transport)
	videoUDP *UDPTransport
	audioUDP *UDPTransport

	prevVideoDTS    int64
	prevAudioDTS    int64
	videoDTSInitialized bool
	audioDTSInitialized bool
	sendCount    int

	// RTCP SR tracking — atomic for lock-free updates in sendPackets hot path
	videoSSRC    uint32
	packetCount  atomic.Uint32
	octetCount   atomic.Uint32
	lastRTPTime  atomic.Uint32

	mu     sync.Mutex
	closed bool
	done   chan struct{}
}

var _ core.Subscriber = (*RTSPSubscriber)(nil)

// NewRTSPSubscriber creates a new RTSP subscriber for TCP interleaved mode.
func NewRTSPSubscriber(id string, info *avframe.MediaInfo, writer io.Writer, videoChannel, audioChannel uint8) (*RTSPSubscriber, error) {
	sub := &RTSPSubscriber{
		id:           id,
		options:      core.DefaultSubscribeOptions(),
		writer:       writer,
		videoChannel: videoChannel,
		audioChannel: audioChannel,
		videoSSRC:    rand.Uint32(),
		done:         make(chan struct{}),
	}

	if info.VideoCodec != 0 {
		pt := codecDefaultPT(info.VideoCodec)
		payloader := pionPayloaderForCodec(info.VideoCodec)
		if payloader != nil {
			sub.videoPacketizer = pionrtp.NewPacketizer(
				pkgrtp.DefaultMTU-12, // payload MTU
				pt,
				0, // SSRC auto-generated by pion
				payloader,
				pionrtp.NewRandomSequencer(),
				90000, // video clock rate
			)
		}
	}

	if info.AudioCodec != 0 {
		pt := codecDefaultPT(info.AudioCodec)
		clockRate := audioClockRate(info)
		payloader := pionPayloaderForCodec(info.AudioCodec)
		if payloader != nil {
			sub.audioPacketizer = pionrtp.NewPacketizer(
				pkgrtp.DefaultMTU-12,
				pt,
				0,
				payloader,
				pionrtp.NewRandomSequencer(),
				clockRate,
			)
		} else {
			// Fallback to custom packetizer for codecs pion doesn't support
			p, err := pkgrtp.NewPacketizer(info.AudioCodec)
			if err != nil {
				return nil, err
			}
			sub.customAudioPkt = p
			sub.customAudioSes = pkgrtp.NewSession(pt, clockRate)
		}
	}

	go sub.rtcpLoop()
	return sub, nil
}

// pionPayloaderForCodec returns a pion Payloader for the given codec, or nil.
func pionPayloaderForCodec(codec avframe.CodecType) pionrtp.Payloader {
	switch codec {
	case avframe.CodecH264:
		return &pioncodecs.H264Payloader{}
	case avframe.CodecVP8:
		return &pioncodecs.VP8Payloader{}
	case avframe.CodecVP9:
		return &pioncodecs.VP9Payloader{}
	case avframe.CodecOpus:
		return &pioncodecs.OpusPayloader{}
	case avframe.CodecG711U, avframe.CodecG711A:
		return &pioncodecs.G711Payloader{}
	case avframe.CodecG722:
		return &pioncodecs.G722Payloader{}
	default:
		return nil
	}
}

func (s *RTSPSubscriber) ID() string                     { return s.id }
func (s *RTSPSubscriber) Options() core.SubscribeOptions { return s.options }

func (s *RTSPSubscriber) OnData(data []byte) error {
	return nil
}

func (s *RTSPSubscriber) Close() error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if !s.closed {
		s.closed = true
		close(s.done)
	}
	return nil
}

// SendFrame packetizes an AVFrame and sends it via TCP interleaved transport.
func (s *RTSPSubscriber) SendFrame(frame *avframe.AVFrame) error {
	s.mu.Lock()
	if s.closed {
		s.mu.Unlock()
		return nil
	}
	s.mu.Unlock()

	if frame.MediaType.IsVideo() {
		return s.sendVideo(frame)
	} else if frame.MediaType.IsAudio() {
		return s.sendAudio(frame)
	}
	return nil
}

func (s *RTSPSubscriber) sendVideo(frame *avframe.AVFrame) error {
	if s.videoPacketizer == nil {
		return nil
	}

	// Sequence header (SPS/PPS) is metadata, not a displayable frame.
	// Skip DTS tracking for it — its RTP timestamp shares with the next keyframe.
	isSeqHeader := frame.FrameType == avframe.FrameTypeSequenceHeader

	// Convert payload to Annex-B for pion's H264Payloader
	payload := pkgrtp.ToAnnexB(frame.Payload, isSeqHeader)

	// Compute sample delta (90kHz clock)
	var samples uint32
	if !isSeqHeader && s.videoDTSInitialized && frame.DTS > s.prevVideoDTS {
		samples = uint32((frame.DTS - s.prevVideoDTS) * 90)
	}
	if !isSeqHeader {
		s.prevVideoDTS = frame.DTS
		s.videoDTSInitialized = true
	}

	pkts := s.videoPacketizer.Packetize(payload, samples)
	return s.sendPackets(pkts, s.videoChannel, s.videoUDP)
}

func (s *RTSPSubscriber) sendAudio(frame *avframe.AVFrame) error {
	if s.audioPacketizer != nil {
		var samples uint32
		if s.audioDTSInitialized && frame.DTS > s.prevAudioDTS {
			clockRate := uint32(44100) // default
			samples = uint32(frame.DTS-s.prevAudioDTS) * clockRate / 1000
		}
		s.prevAudioDTS = frame.DTS
		s.audioDTSInitialized = true
		pkts := s.audioPacketizer.Packetize(frame.Payload, samples)
		return s.sendPackets(pkts, s.audioChannel, s.audioUDP)
	}

	// Fallback to custom packetizer
	if s.customAudioPkt == nil {
		return nil
	}
	pkts, err := s.customAudioPkt.Packetize(frame, pkgrtp.DefaultMTU)
	if err != nil {
		return err
	}
	wrapped := s.customAudioSes.WrapPackets(pkts, frame.DTS)
	return s.sendPackets(wrapped, s.audioChannel, s.audioUDP)
}

func (s *RTSPSubscriber) sendPackets(pkts []*pionrtp.Packet, channel uint8, udp *UDPTransport) error {
	for _, pkt := range pkts {
		data, err := pkt.Marshal()
		if err != nil {
			return err
		}
		s.sendCount++
		s.packetCount.Add(1)
		s.octetCount.Add(uint32(len(pkt.Payload)))
		s.lastRTPTime.Store(pkt.Timestamp)
		if udp != nil {
			if err := udp.SendRTP(data); err != nil {
				return err
			}
		} else {
			if err := WriteInterleaved(s.writer, channel, data); err != nil {
				return err
			}
		}
	}
	return nil
}

// rtcpLoop sends periodic RTCP Sender Reports on the video RTCP channel.
func (s *RTSPSubscriber) rtcpLoop() {
	ticker := time.NewTicker(5 * time.Second)
	defer ticker.Stop()
	for {
		select {
		case <-ticker.C:
			s.mu.Lock()
			if s.closed {
				s.mu.Unlock()
				return
			}
			s.mu.Unlock()

			pktCount := s.packetCount.Load()
			octCount := s.octetCount.Load()
			rtpTime := s.lastRTPTime.Load()

			ntpTime := toNTP(time.Now())
			sr := pkgrtp.BuildSR(s.videoSSRC, ntpTime, rtpTime, pktCount, octCount)
			if s.videoUDP != nil {
				s.videoUDP.SendRTCP(sr)
			} else {
				rtcpChannel := s.videoChannel + 1 // odd channel = RTCP
				WriteInterleaved(s.writer, rtcpChannel, sr)
			}
		case <-s.done:
			return
		}
	}
}

// toNTP converts a time.Time to NTP timestamp (RFC 3550 format).
func toNTP(t time.Time) uint64 {
	// NTP epoch is Jan 1, 1900. Unix epoch is Jan 1, 1970.
	const ntpEpochOffset = 2208988800
	secs := uint64(t.Unix()) + ntpEpochOffset
	frac := uint64(t.Nanosecond()) * (1 << 32) / 1e9
	return secs<<32 | frac
}


// Done returns a channel that is closed when the subscriber is closed.
func (s *RTSPSubscriber) Done() <-chan struct{} {
	return s.done
}

// audioClockRate returns the RTP clock rate for the audio codec.
func audioClockRate(info *avframe.MediaInfo) uint32 {
	switch info.AudioCodec {
	case avframe.CodecOpus:
		return 48000
	case avframe.CodecG711U, avframe.CodecG711A, avframe.CodecG722, avframe.CodecG729, avframe.CodecSpeex:
		return 8000
	case avframe.CodecMP3:
		return 90000
	case avframe.CodecAAC:
		if info.SampleRate > 0 {
			return uint32(info.SampleRate)
		}
		return 44100
	default:
		return 44100
	}
}
